Startlette: capture custom request response headers in span attributes
open-telemetry/opentelemetry-python-contrib pull request #1046
Opened 2022-04-08 21:19 UTC by sanketmehta28

# Description

This PR contains py tests for Starlette framework. Actual code has been merged in this PR: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1004
It also contains the doc update for Startlette framework

Fixes # (917)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Added below unit tests for request and response headers for both http and websocket applications.

- [x] Test A: check for request header which is set in OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST env variable, is present in the span as attribute
- [x] Test B: check for request header which is NOT set in OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST env variable, is NOT present in the span as attribute
- [x] Test C: check for response header which is set in OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_RESPONSE env variable, is present in the span as attribute
- [x] Test D: check for response header which is NOT set in OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_RESPONSE env variable, is NOT present in the span as 
attribute

- Also added test for NoOpTracerProvider as well

# Does This PR Require a Core Repo Change?

- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [x] Documentation has been updated

2022-04-11 12:51 UTC, sanketmehta28 commented
@open-telemetry/python-approvers:  Please do review this PR and if it looks fine, please do merge it

2022-04-12 11:37 UTC, sanketmehta28 commented
@open-telemetry/python-approvers: All conflicts are resolved. Please do review this

2022-04-12 13:31 UTC, srikanthccv requested changes

2022-04-12 13:31 UTC, srikanthccv commented on instrumentation/opentelemetry-instrumentation-asgi/src/opentelemetry/instrumentation/asgi/__init__.py
> -
Why are you deleting this?

2022-04-12 13:31 UTC, srikanthccv commented on instrumentation/opentelemetry-instrumentation-falcon/src/opentelemetry/instrumentation/falcon/__init__.py
> -
Same

2022-04-12 13:31 UTC, srikanthccv commented on instrumentation/opentelemetry-instrumentation-tornado/src/opentelemetry/instrumentation/tornado/__init__.py
> -Request header names in tornado are case insensitive. So, giving header name as ``CUStomHeader`` in environment variable will be able capture header with name ``customheader``.
Same thing everywhere

2022-04-12 18:38 UTC, owais approved these changes

2022-04-12 22:55 UTC, lzchen commented on instrumentation/opentelemetry-instrumentation-asgi/src/opentelemetry/instrumentation/asgi/__init__.py
> +API
Duplicate?

2022-04-12 22:55 UTC, lzchen commented on instrumentation/opentelemetry-instrumentation-fastapi/tests/test_fastapi_instrumentation.py
> +        self.assertEqual(len(span_list), 0)
Add a blank line here.

2022-04-13 12:55 UTC, sanketmehta28 commented
@lzchen: all your comments are addressed. Please do review and merge this PR

2022-04-13 14:45 UTC, srikanthccv approved these changes

2022-04-13 14:45 UTC, srikanthccv commented on instrumentation/opentelemetry-instrumentation-starlette/tests/test_starlette_instrumentation.py
> +        for key, _ in not_expected.items():
```suggestion
        for key in not_expected:
```

2022-04-13 17:08 UTC, lzchen approved these changes

2022-04-18 18:12 UTC, merged