Celery add support for anon tasks
open-telemetry/opentelemetry-python-contrib pull request #1052
Opened 2022-04-13 17:47 UTC by goatsthatcode

# Description

This changes the way spans are initialized for the celery instrumentation hooks and handles the case where Celery tasks are not available in the registry and called anonymously using the `signature()` or `send_task()`

Fixes #1002

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Ran changes against reproduced issue in repo linked in issue -> https://github.com/goatsthatcode/opentelemetry-instrumentation-celery-example
- [x] Added Unit Test to cover new conditional branch
- [x] Passed existing test suite

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

2022-04-16 14:13 UTC, srikanthccv reviewed
@goatsthatcode Did you run the reproducible example provided in https://github.com/open-telemetry/opentelemetry-python-contrib/issues/609 and can confirm it is fixed?

2022-04-18 08:27 UTC, blumamir commented on instrumentation/opentelemetry-instrumentation-celery/src/opentelemetry/instrumentation/celery/utils.py
> +    if task is None:
I'll copy the comment I wrote on the original PR in your fork for the wide discussion:

> I think the effect of this return statement is that the span (along with activation) will not be recorded into the CTX_KEY, which means that a later invocation of the _trace_after_publish signal will not be able to retrieve_span thus will not end the span.
Am I missing something?

Didn't actually try to run it, so I might just not fully understand the details of what causes the "publish" span to be ended.

2022-04-28 15:50 UTC, goatsthatcode commented
Hi guys, sorry for the radio silence here. I got really sick this last week so was offline for a bit. I am picking up the remaining pieces today to make sure this at least ready to be merged (unless any additional comments come up).  Sorry for the delay :D

2022-05-01 16:43 UTC, sanketmehta28 commented
Please resolves build errors.

2022-05-17 12:40 UTC, yousifd commented
@goatsthatcode can you please resolve the build errors?

2022-05-23 03:23 UTC, Vivalldi requested changes
I _believe_ these will take care of the linting issues

2022-05-26 16:23 UTC, sanketmehta28 commented
There are still some lint and generate build issues. Please do resolve them

2022-08-05 15:31 UTC, rahuldimri commented on instrumentation/opentelemetry-instrumentation-celery/tests/test_tasks.py
> +        )
Are we still working on this issue ?

2022-10-23 07:57 UTC, naormalca commented
@goatsthatcode i'm very interested in this fix, are you still working on it? if not, could i take it from here?

2022-12-10 02:00 UTC, srikanthccv commented
succeeded by #1407

2022-12-10 02:00 UTC, closed without merging