[BugFix] Close issue #1195, "Invalid type Exchange for attribute value. Expected one of bool, str, bytes, int, float or a sequence of those types" warning when Celery task runs another celery task
open-telemetry/opentelemetry-python-contrib pull request #1196
Opened 2022-07-18 13:57 UTC by Heatstealer

# Description
There are a lot of serialization errors when celery task run another celery task in case when you are using custom Exchange and custom Queue.
Span tags could be only `bool, str, bytes, int, float`.

Fixes #https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1195

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Tested on the environment where issue had happened.
Added unit test

# Does This PR Require a Core Repo Change?
- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:
- [x] Followed the style guidelines of this project
- [x] Changelogs have been updated
- [x] Unit tests have been added
- [ ] Documentation has been updated

2022-07-18 17:42 UTC, ocelotl requested changes
Thanks for the fix! We need at least one test case that proves this fix does its intended purpose.

2022-07-18 17:43 UTC, ocelotl commented
Also, please sign the CLA :v:

2022-09-20 16:27 UTC, lzchen commented
@Heatstealer 
Are you still working on this?

2023-02-04 19:23 UTC, srikanthccv commented
@Heatstealer ping, please sign the CLA and add the CHANGELOG entry.

2023-07-12 09:51 UTC, poofeg commented
> Thanks for the fix! We need at least one test case that proves this fix does its intended purpose.

@ocelotl
Are all the requirements met?

2026-03-25 15:57 UTC, sterchelen commented
hello there
I'd like to know what is blocking us to merge this PR?
cc @srikanthccv @Heatstealer @ocelotl 
Thx 🙇🏼

2026-04-03 14:54 UTC, MikeGoldsmith commented
Hi @sterchelen — the fix itself addresses a real bug, but there are a few things still needed before it can merge:

1. Test assertion bug — celery.exchange is set from Exchange("celery_exchange") but the test asserts "celery_queue". Should be "celery_exchange".
2. Narrow fix — the `isinstance` check only covers Exchange/Queue from `celery.backends.amqp`, but the issue mentions kombu.Exchange/kombu.Queue which may be different classes. A nicer approach might be catch any non-primitive type:
```
  if not isinstance(value, (bool, str, bytes, int, float)):
      value = str(value)
```
3. CHANGELOG — the entry is under an already-released version (1.17.0/0.38b0), needs to move to Unreleased.
4. The PR will also need a rebase given its age.

@Heatstealer — happy to help land this if you're able to make these changes 😄

2026-04-03 15:29 UTC, closed without merging

2026-04-03 16:06 UTC, Heatstealer commented
@MikeGoldsmith 

> Hi @sterchelen — the fix itself addresses a real bug, but there are a few things still needed before it can merge:
> 
>     1. Test assertion bug — celery.exchange is set from Exchange("celery_exchange") but the test asserts "celery_queue". Should be "celery_exchange".
> 
>     2. Narrow fix — the `isinstance` check only covers Exchange/Queue from `celery.backends.amqp`, but the issue mentions kombu.Exchange/kombu.Queue which may be different classes. A nicer approach might be catch any non-primitive type:
> 
> 
> ```
>   if not isinstance(value, (bool, str, bytes, int, float)):
>       value = str(value)
> ```
> 
>     3. CHANGELOG — the entry is under an already-released version (1.17.0/0.38b0), needs to move to Unreleased.
> 
>     4. The PR will also need a rebase given its age.
> 
> 
> @Heatstealer — happy to help land this if you're able to make these changes 😄

1. Fixed test
2. I think it is good idea, added json-serializable fields check also
3. moved to Unreleased
4. PR had been rebased

But I accidentally created a new one PR, so this one had been closed automatically.
New PR: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/4393