psycopg2-binary support
open-telemetry/opentelemetry-python-contrib pull request #1422
Opened 2022-10-29 18:09 UTC by kamilkrampa

# Description

Inspired by this [comment](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/610#issuecomment-953207184). I changed the idea slightly to OR inner tuples, it seemed to be easier to do but let me know what do you think about it.

Fixes #610 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Added unit tests
- Instrument any app with psycopg2-binary installed

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [X] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [X] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [X] Unit tests have been added
- [ ] Documentation has been updated

2024-12-31 09:16 UTC, Kludex requested changes
A `test-requirements.txt` file needs to be added to test with only `psycopg2-binary`, I guess.

2024-12-31 09:16 UTC, Kludex commented
Oh, this is 2 years old. 😢

Still valid tho.

2024-12-31 15:48 UTC, xrmx requested changes

2024-12-31 15:48 UTC, xrmx commented on instrumentation/opentelemetry-instrumentation-psycopg2/src/opentelemetry/instrumentation/psycopg2/package.py
> +_instruments = (("psycopg2 >= 2.7.3.1", "psycopg2-binary >= 2.7.3.1"),)
```suggestion
_instruments = ("psycopg2 >= 2.7.3.1", "psycopg2-binary >= 2.7.3.1")
```
This is what the kafka-python is doing, please take a look at opentelemetry-instrumentation-kafka-python/pyproject.toml, with that updated you should be able to drop the dependencies,py changes.

2025-01-14 16:31 UTC, joshowen commented on instrumentation/opentelemetry-instrumentation-psycopg2/src/opentelemetry/instrumentation/psycopg2/package.py
> +_instruments = (("psycopg2 >= 2.7.3.1", "psycopg2-binary >= 2.7.3.1"),)
I've done the minimal implementation here https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1422

2025-01-27 12:39 UTC, closed without merging