Mertics instrumentation dbapi
open-telemetry/opentelemetry-python-contrib pull request #1620
Opened 2023-02-03 08:06 UTC by siddhikhapare

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [ ] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

2023-02-03 08:08 UTC, siddhikhapare commented
Fixes #1158

2023-02-03 11:51 UTC, srikanthccv requested changes
This implementation is incorrect. Please take a look at the other instrumentation for reference. Either close this and reimplement by taking some help or make it draft.

2023-02-03 11:51 UTC, srikanthccv commented on instrumentation/opentelemetry-instrumentation-dbapi/src/opentelemetry/instrumentation/dbapi/__init__.py
> +from opentelemetry.sdk.metrics import MeterProvider
Why is SDK imported here in the instrumentation? Instrumentation never uses SDK.

2023-02-03 11:51 UTC, srikanthccv commented on instrumentation/opentelemetry-instrumentation-dbapi/src/opentelemetry/instrumentation/dbapi/__init__.py
> +meter = MeterProvider().get_meter(__name__)
Why is new meter provider instantiated here?

2023-02-03 11:51 UTC, srikanthccv commented on instrumentation/opentelemetry-instrumentation-dbapi/src/opentelemetry/instrumentation/dbapi/__init__.py
What's happening here?

2023-02-03 11:51 UTC, srikanthccv commented on instrumentation/opentelemetry-instrumentation-dbapi/src/opentelemetry/instrumentation/dbapi/__init__.py
> +)
Why are you creating an instance of DBAPI integration here?

2023-02-03 11:51 UTC, srikanthccv commented on instrumentation/opentelemetry-instrumentation-dbapi/src/opentelemetry/instrumentation/dbapi/__init__.py
> +pending_requests_updowncounter.subtract(1)
Why are these in global scope? I am not following what is happening here?

2023-02-04 11:20 UTC, siddhikhapare commented
@srikanthccv I will make changes as per your suggestions. I am going through document form here https://opentelemetry-python-contrib.readthedocs.io/en/latest/_modules/opentelemetry/instrumentation/flask.html#FlaskInstrumentor.

2023-02-04 15:18 UTC, siddhikhapare commented
@srikanthccv Can you tell me that what to pass as metrics attributes? Do I pass span attributes or connection_attributes?

2023-02-04 16:59 UTC, siddhikhapare commented
@srikanthccv As I understood that from given code provides is integration of openTelemetry to trace and monitor database. trace_integration is function that integrates database with otel. The wrap_connect function wraps the connect method of the database to trace database connections. The unwrap_connect function unwraps the previously wrapped connect method. The instrument_connection function instruments an already established database connection to trace and monitor it.
class DatabaseApiIntegration used to wrap database connections, set connection attributes, and trace database. get_traced_connection_proxy function returns a wrapped connection object to be used for tracing. The code also uses a third-party library wrapt to wrap functions. so  Do I get attributes for metrics from connection_attributes to record in histogram? Can you help me in what to use. Thank you.

2023-02-06 17:40 UTC, closed without merging