#240 Rename "host.port" attribute to "net.host.port"
open-telemetry/opentelemetry-python-contrib pull request #242
Opened 2020-12-09 12:52 UTC by malafeev

# Description

According to Semantic Conventions https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/semantic_conventions/http-metrics.md
attribute "net.host.port" should be used instead of "host.port"

Fixes #240

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] tox -e test-instrumentation-wsgi
- [x] tox -e test-instrumentation-pyramid
- [x] tox -e test-instrumentation-flask
- [x] tox -e test-instrumentation-falcon
- [x] tox -e test-instrumentation-asgi 

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [x] Documentation has been updated

2020-12-09 16:55 UTC, codeboten requested changes
Minor change to the changelog, otherwise the PR looks great!

2020-12-09 16:55 UTC, codeboten commented on CHANGELOG.md
> +- - `opentelemetry-ext-http-requests` Rename package to opentelemetry-ext-requests
this looks like a copy and paste typo?

2020-12-10 10:56 UTC, malafeev commented on CHANGELOG.md
> +- - `opentelemetry-ext-http-requests` Rename package to opentelemetry-ext-requests
fixed

2020-12-10 16:44 UTC, codeboten approved these changes
Thanks!

2020-12-10 18:52 UTC, lzchen approved these changes

2020-12-11 01:16 UTC, ocelotl approved these changes
Thanks, @malafeev :+1:

2020-12-11 06:29 UTC, malafeev commented
can anybody merge this PR?

2020-12-11 15:55 UTC, merged