Fix dependency notes in tox.ini
open-telemetry/opentelemetry-python-contrib pull request #2481
Opened 2024-04-30 15:38 UTC by ocelotl

Fixes #24800

2024-04-30 16:20 UTC, aabmass requested changes

2024-04-30 16:20 UTC, aabmass commented on tox.ini
> -    ; 2: falcon >=3.0.0,<4.0.0
I thought the goal of these comments was to preserve the actual range so when it comes time to upgrade the pinned version, we can make sure it meets this requirement?

2024-04-30 16:20 UTC, aabmass commented on tox.ini
> +    ; 2: Flask==3.0.2 Werkzeug==3.0.1
I'm a bit confused what's going on here. This version constraint is impossible to fulfill

How did we get here? 😅

2024-04-30 16:20 UTC, aabmass commented on tox.ini
> -    ; 2: Flask >=3.0.0 Werkzeug >=3.0.0
These are the same number, something went wrong?

2024-09-03 19:27 UTC, ocelotl commented
I won't be workin on this PR for the foreseeable future, closing.

2024-09-03 19:27 UTC, closed without merging