switch setter for injecting headers into propagator
open-telemetry/opentelemetry-python-contrib pull request #264
Opened 2020-12-18 03:57 UTC by alertedsnake

# Description

Occasionally not all of the headers available to botocore are strings - I've noticed this when a call is being made with an active span passed from a different application (specifically via gRPC).  Botocore does allow this, using the `add_header` method rather than `__setitem__`.  According to the docs for `botocore.compat.HTTPHeaders`:

```
If a parameter value contains non-ASCII characters it can be specified
as a three-tuple of (charset, language, value), in which case it will be
encoded according to RFC2231 rules.  Otherwise it will be encoded using
the utf-8 charset and a language of ''
```

Whereas using `__setitem__` does not do this conversion.

I'm not convinced this is the right place to fix this, however - I've only encountered it in the situation described in #262, and haven't been able to find what would be passing in a non-string header in the first place.  I'll be happy to dig more if anyone has a better suggestion, but as far as I can tell, this is also an innocuous change.

One question I have though is about how I could test this - I don't know how to simulate (in the botocore tests) having an active trace passed through from another application, so advice on this would be welcome.

Fixes #262
## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

All existing tests still pass, and I've been working with the situation described in #262 

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [X] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [X] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ ] Documentation has been updated

2020-12-19 21:24 UTC, toumorokoshi requested changes
The code seems innocuous, but we should probably root cause + add a test to make sure this is right, as you mentioned. I'll comment more on the other issue.

2020-12-19 21:24 UTC, toumorokoshi commented on instrumentation/opentelemetry-instrumentation-botocore/src/opentelemetry/instrumentation/botocore/__init__.py
> +    propagators.inject(type(headers).add_header, headers)
I don't have a lot of context on this, but we should probably add at least a test for the case you're running into.

From https://github.com/open-telemetry/opentelemetry-python-contrib/issues/262, it sounds like the most relevant part is the DyanamoDB API call. have you tried adding a mock DynamiDB api call (moto [looks to support dynamodb](https://github.com/spulec/moto/tree/master/moto/dynamodb))? It seems like a call that maps what you're executing in your service should trigger the error.

2020-12-19 21:24 UTC, toumorokoshi commented on instrumentation/opentelemetry-instrumentation-botocore/src/opentelemetry/instrumentation/botocore/__init__.py
> +    propagators.inject(type(headers).add_header, headers)
Taking a closer look, the part I'm a little unclear on is, as you mentioned, what is actually causing this. I have a feeling something was injected that should not have been by the propagator. I'll comment more on the issue.

2020-12-22 17:35 UTC, alertedsnake commented
Closing this, it's not the root cause of #262 and so doesn't seem necessary.

2020-12-22 17:35 UTC, closed without merging