Adds back retry_attempts to botocore
open-telemetry/opentelemetry-python-contrib pull request #275
Opened 2020-12-24 02:57 UTC by thomasdesr

# Description

The `retry_attempts` field in `instrumentation-botocore` previously reported how many retries it took botocore to complete an API request (e.g. if the client is rate limited).

It was lost during this refactor https://github.com/open-telemetry/opentelemetry-python-contrib/pull/150 & and I can't find any comments or issues saying it was intentionally dropped (sorry if I missed this!).

So this PR adds it back :D

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Manual test: https://gist.github.com/thomasdesr/08849445953715f38cf6d29d17b00adf
- Updated the existing botocore automated tests

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [x] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [x] Unit tests have been added
- [ ] Documentation has been updated

(Lmk if you want me to add this to the changelog)

2020-12-26 06:32 UTC, toumorokoshi requested changes
for now, I'd leave out "aws.retry_attempts", because it's not specific to AWS.

2020-12-26 06:32 UTC, toumorokoshi commented on instrumentation/opentelemetry-instrumentation-botocore/src/opentelemetry/instrumentation/botocore/__init__.py
> +                            "aws.retry_attempts", metadata["RetryAttempts"],
Is `aws.retry_attempts` the right choice? The [original code](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/150/files#diff-05ef2bbeb79bb2d595bf8a3f7fa2d475d0f34f80804e5e1ba0d9a253d2c0e0e3L154) seems to just have retry_attempts.

That makes sense to me, as retry attempts, albeit behavior in AWS's boto, is not really in aws-specific construct.

retry attempts actually seems quite generic, it probably should be a semantic convention in the spec.

2020-12-26 15:52 UTC, thomasdesr commented
Thanks for taking a look! Moved back to just plain `retry_attempts` :D

2020-12-30 14:50 UTC, toumorokoshi approved these changes
Thanks! LGTM.

2021-01-04 15:44 UTC, codeboten requested changes
Thanks for the PR! It looks great, if you could add an entry to the changelog for this, I can approve and merge.

2021-01-06 01:19 UTC, codeboten approved these changes
Thanks!

2021-01-06 01:21 UTC, thomasdesr commented
Thanks for the reviews & project in general :D

2021-01-06 01:27 UTC, merged