Fix broken RST docs
open-telemetry/opentelemetry-python-contrib pull request #3062
Opened 2024-12-03 07:44 UTC by buger

# Description
Fix broken RST docs, and improve the examples

Fix https://github.com/open-telemetry/opentelemetry-python-contrib/issues/3061

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Build docs locally and validated rendering

# Does This PR Require a Core Repo Change?

- [ ] Yes. - Link to PR: 
- [x] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [x] Documentation has been updated

2024-12-03 09:14 UTC, xrmx approved these changes

2024-12-03 11:42 UTC, emdneto requested changes
Thanks for the PR. I think even with that fix, we'll still face broken RSTs because the actual docs come from [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-confluent-kafka/src/opentelemetry/instrumentation/confluent_kafka/__init__.py#L21) for example. So, the correct fix should be in the respective doc at __init__.py of each package.

2024-12-03 18:46 UTC, buger commented
@emdneto done!

2024-12-03 19:13 UTC, emdneto commented on instrumentation/opentelemetry-instrumentation-aiokafka/src/opentelemetry/instrumentation/aiokafka/__init__.py
>  for example:
I think we can remove from L38 to L46 here.

2024-12-03 19:14 UTC, emdneto commented on instrumentation/opentelemetry-instrumentation-confluent-kafka/src/opentelemetry/instrumentation/confluent_kafka/__init__.py
>  The _instrument method accepts the following keyword args:
Same here. From L59 to L71

2024-12-03 19:15 UTC, emdneto commented on instrumentation/opentelemetry-instrumentation-kafka-python/src/opentelemetry/instrumentation/kafka/__init__.py
>  for example:
Same here from L38 to L46

2024-12-05 10:28 UTC, xrmx approved these changes
I think we can get the syntax fixes now and revise the content later

2024-12-05 12:09 UTC, emdneto approved these changes

2024-12-05 12:53 UTC, merged