Add create context key to contrib
open-telemetry/opentelemetry-python-contrib pull request #502
Opened 2021-05-21 22:18 UTC by eunice98k

# Description

This PR makes the corresponding changes from otel-python [open-telemetry/opentelemetry-python#1372](https://github.com/open-telemetry/opentelemetry-python/pull/1853) in the contrib to implement `create_key` functionality as noted [here](https://github.com/open-telemetry/opentelemetry-python/issues/1737).

# How Has This Been Tested?

`tox` was ran to ensure the new and existing unit tests all pass.

2021-05-24 16:53 UTC, lzchen commented on CHANGELOG.md
> +- Added support for CreateKey functionality.
Nit: Please include this in the 'Added' section.

2021-05-24 16:54 UTC, lzchen commented on exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/spanprocessor.py
> +EXPORT_KEY = create_key("suppress_instrumentation")
```suggestion
_EXPORT_KEY = create_key("suppress_instrumentation")
```

2021-05-24 16:58 UTC, lzchen approved these changes

2021-05-25 16:07 UTC, codeboten requested changes
Just wanted to confirm my understanding here, the `suppress_instrumentation` context key was being utilized previously by the instrumentations to check if somewhere the SDK had set it. But from the looks here, this change updates the code to create separate keys for each instrumentation.

I believe this mean that this change breaks the functionality we currently have where the span process can set the `suppress_instrumentation` key before export to prevent the exporter from generating spans. https://github.com/open-telemetry/opentelemetry-python/blob/77c9867dcb0f3179c1b395729aae6aec2c3133a0/opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py#L89 

Can you confirm? If so, we should figure out the right way to move forward to not break this functionality.

2021-05-25 17:45 UTC, eunice98k commented
> Just wanted to confirm my understanding here, the `suppress_instrumentation` context key was being utilized previously by the instrumentations to check if somewhere the SDK had set it. But from the looks here, this change updates the code to create separate keys for each instrumentation.
> 
> I believe this mean that this change breaks the functionality we currently have where the span process can set the `suppress_instrumentation` key before export to prevent the exporter from generating spans. https://github.com/open-telemetry/opentelemetry-python/blob/77c9867dcb0f3179c1b395729aae6aec2c3133a0/opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py#L89
> 
> Can you confirm? If so, we should figure out the right way to move forward to not break this functionality.

Sorry I didn't know the full context behind the `suppress_instrumentation` context key before making the changes. Yes your understanding is correct in that a new key is created for each instrumentation. This was because now with the `create_key` functionality creates a unique key name, which is now not simply `suppress_instrumentation`. 

What I can do is since in the otel-python PR, I am creating a unique `suppress_instrumentation` key, I could simply export this key to each instrumentation that uses it instead of calling `create_key` each time. (I will also rename this from EXPORT_KEY to _SUPPRESS_INSTRUMENTATION_KEY.)
https://github.com/open-telemetry/opentelemetry-python/pull/1853/files#diff-ccdfba02d42525f2fee85e7369c94b7c4976ec22079248bbddf610cd11435739R41

2021-05-26 00:02 UTC, ocelotl commented
> > Just wanted to confirm my understanding here, the `suppress_instrumentation` context key was being utilized previously by the instrumentations to check if somewhere the SDK had set it. But from the looks here, this change updates the code to create separate keys for each instrumentation.
> > I believe this mean that this change breaks the functionality we currently have where the span process can set the `suppress_instrumentation` key before export to prevent the exporter from generating spans. https://github.com/open-telemetry/opentelemetry-python/blob/77c9867dcb0f3179c1b395729aae6aec2c3133a0/opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py#L89
> > Can you confirm? If so, we should figure out the right way to move forward to not break this functionality.
> 
> Sorry I didn't know the full context behind the `suppress_instrumentation` context key before making the changes. Yes your understanding is correct in that a new key is created for each instrumentation. This was because now with the `create_key` functionality creates a unique key name, which is now not simply `suppress_instrumentation`.
> 
> What I can do is since in the otel-python PR, I am creating a unique `suppress_instrumentation` key, I could export this key to each instrumentation that uses it instead of calling `create_key` each time. (I will also rename this from EXPORT_KEY to _SUPPRESS_INSTRUMENTATION_KEY.)
> https://github.com/open-telemetry/opentelemetry-python/pull/1853/files#diff-ccdfba02d42525f2fee85e7369c94b7c4976ec22079248bbddf610cd11435739R41
> 
> Let me know if you think this is alright!

Yes, this makes sense :+1:

2021-05-26 17:30 UTC, codeboten commented
> > Just wanted to confirm my understanding here, the `suppress_instrumentation` context key was being utilized previously by the instrumentations to check if somewhere the SDK had set it. But from the looks here, this change updates the code to create separate keys for each instrumentation.
> > I believe this mean that this change breaks the functionality we currently have where the span process can set the `suppress_instrumentation` key before export to prevent the exporter from generating spans. https://github.com/open-telemetry/opentelemetry-python/blob/77c9867dcb0f3179c1b395729aae6aec2c3133a0/opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py#L89
> > Can you confirm? If so, we should figure out the right way to move forward to not break this functionality.
> 
> Sorry I didn't know the full context behind the `suppress_instrumentation` before making the changes. Yes your understanding is correct in that a new key is created for each instrumentation. This was because now with the `create_key` functionality creates a unique key name, which is now not simply `suppress_instrumentation`.
> 
> What I can do is since in the otel-python PR, I am creating a unique `suppress_instrumentation` key, I could export this key to each instrumentation that uses it instead of calling `create_key` each time. (I will also rename this from EXPORT_KEY to _SUPPRESS_INSTRUMENTATION_KEY.)
> https://github.com/open-telemetry/opentelemetry-python/pull/1853/files#diff-ccdfba02d42525f2fee85e7369c94b7c4976ec22079248bbddf610cd11435739R41
> 
> Let me know if you think this is alright!

The problem with exporting the key from the SDK is that the instrumentations will then depend on the SDK, which I don't believe they do today. This should likely be part of the API instead, this was discussed in the specification here: https://github.com/open-telemetry/opentelemetry-specification/issues/530

I'll add this to the agenda to discuss it at Thursday's SIG meeting.

2021-05-26 23:27 UTC, ocelotl commented
> > > Just wanted to confirm my understanding here, the `suppress_instrumentation` context key was being utilized previously by the instrumentations to check if somewhere the SDK had set it. But from the looks here, this change updates the code to create separate keys for each instrumentation.
> > > I believe this mean that this change breaks the functionality we currently have where the span process can set the `suppress_instrumentation` key before export to prevent the exporter from generating spans. https://github.com/open-telemetry/opentelemetry-python/blob/77c9867dcb0f3179c1b395729aae6aec2c3133a0/opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py#L89
> > > Can you confirm? If so, we should figure out the right way to move forward to not break this functionality.
> > 
> > 
> > Sorry I didn't know the full context behind the `suppress_instrumentation` before making the changes. Yes your understanding is correct in that a new key is created for each instrumentation. This was because now with the `create_key` functionality creates a unique key name, which is now not simply `suppress_instrumentation`.
> > What I can do is since in the otel-python PR, I am creating a unique `suppress_instrumentation` key, I could export this key to each instrumentation that uses it instead of calling `create_key` each time. (I will also rename this from EXPORT_KEY to _SUPPRESS_INSTRUMENTATION_KEY.)
> > https://github.com/open-telemetry/opentelemetry-python/pull/1853/files#diff-ccdfba02d42525f2fee85e7369c94b7c4976ec22079248bbddf610cd11435739R41
> > Let me know if you think this is alright!
> 
> The problem with exporting the key from the SDK is that the instrumentations will then depend on the SDK, which I don't believe they do today. This should likely be part of the API instead, this was discussed in the specification here: [open-telemetry/opentelemetry-specification#530](https://github.com/open-telemetry/opentelemetry-specification/issues/530)
> 
> I'll add this to the agenda to discuss it at Thursday's SIG meeting.

Hm, yeah, good point, @codeboten. I think [this](https://github.com/open-telemetry/opentelemetry-specification/pull/1653) is the PR that added the suppress instrumentation key to the API.

2021-06-02 16:29 UTC, lzchen commented on instrumentation/opentelemetry-instrumentation-requests/src/opentelemetry/instrumentation/requests/__init__.py
> +_SUPPRESS_HTTP_INSTRUMENTATION_KEY = context.create_key(
Remove this?

2021-06-02 16:31 UTC, lzchen commented on opentelemetry-instrumentation/src/opentelemetry/instrumentation/utils.py
> +_SUPPRESS_INSTRUMENTATION_KEY = create_key("suppress_instrumentation")
Can we leave a comment saying that this is a temporary solution, and we are waiting on a decision to how we are handling supressing instrumentations?

2021-06-02 16:32 UTC, lzchen approved these changes

2021-06-03 17:55 UTC, ocelotl approved these changes
Just please add the `FIXME`, it makes it easier to find stuff that is to be fixed later.

2021-06-03 17:55 UTC, ocelotl commented on opentelemetry-instrumentation/src/opentelemetry/instrumentation/utils.py
> +# This is a temporary location for the suppress instrumentation key.
```suggestion
# FIXME This is a temporary location for the suppress instrumentation key.
```

2021-06-11 16:50 UTC, merged