Adding web.py example
open-telemetry/opentelemetry-python-contrib pull request #523
Opened 2021-06-01 16:31 UTC by kamalhussain

# Description

Adding a Web.py example for the wsgi instrumentation module.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

It is  a documentation change only.

# Does This PR Require a Core Repo Change?

- [ ] No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [ * ] Followed the style guidelines of this project
- [ ] Changelogs have been updated
- [ ] Unit tests have been added
- [ * ] Documentation has been updated

2021-06-01 16:33 UTC, codeboten reviewed
Nice, thanks for the contribution!

2021-06-01 16:43 UTC, lonewolf3739 commented
Please update the description with `Fixes #519`. It automatically closes the linked issue.

2021-06-01 22:24 UTC, owais approved these changes

2021-06-01 22:56 UTC, codeboten approved these changes

2021-06-02 17:38 UTC, ocelotl requested changes

2021-06-02 17:38 UTC, ocelotl commented on instrumentation/opentelemetry-instrumentation-wsgi/src/opentelemetry/instrumentation/wsgi/__init__.py
> +	    server.start()
```suggestion
    import web
    from opentelemetry.instrumentation.wsgi import OpenTelemetryMiddleware
    from cheroot import wsgi

    urls = ('/', 'index')


    class index:

        def GET(self):
            return "Hello, world!"


    if __name__ == "__main__":
        app = web.application(urls, globals())
        func = app.wsgifunc()

        func = OpenTelemetryMiddleware(func)

        server = wsgi.WSGIServer(
            ("localhost", 5100), func, server_name="localhost"
        )
        server.start()
```

This code mixes tabs and spaces among other things, please use this suggestion instead.

2021-06-10 19:00 UTC, ocelotl approved these changes

2021-06-17 15:31 UTC, merged