[tests] use _NoOpTracer and _NoOpTracerProvider
open-telemetry/opentelemetry-python-contrib pull request #860
Opened 2022-01-11 19:17 UTC by codeboten

# Description

Follow up to https://github.com/open-telemetry/opentelemetry-python/pull/2363, not necessary for that change, but removes deprecation warnings.

2022-01-11 20:35 UTC, lzchen approved these changes

2022-01-18 17:13 UTC, ocelotl requested changes

2022-01-18 17:13 UTC, ocelotl commented on instrumentation/opentelemetry-instrumentation-grpc/tests/test_client_interceptor.py
> +                trace._NoOpTracer()
```suggestion
                trace.NoOpTracer()
```

2022-01-18 17:13 UTC, ocelotl commented on instrumentation/opentelemetry-instrumentation-httpx/tests/test_httpx_integration.py
> +                    tracer_provider=trace._NoOpTracerProvider()
```suggestion
                    tracer_provider=trace.NoOpTracerProvider()
```

2022-01-18 17:13 UTC, ocelotl commented on instrumentation/opentelemetry-instrumentation-httpx/tests/test_httpx_integration.py
> +                    tracer_provider=trace._NoOpTracerProvider()
```suggestion
                    tracer_provider=trace.NoOpTracerProvider()
```

2022-01-18 17:13 UTC, ocelotl commented on instrumentation/opentelemetry-instrumentation-requests/tests/test_requests_integration.py
> +                tracer_provider=trace._NoOpTracerProvider()
```suggestion
                tracer_provider=trace.NoOpTracerProvider()
```

2022-01-18 17:13 UTC, ocelotl commented on instrumentation/opentelemetry-instrumentation-urllib/tests/test_urllib_integration.py
> +                tracer_provider=trace._NoOpTracerProvider()
```suggestion
                tracer_provider=trace.NoOpTracerProvider()
```

2022-01-27 21:04 UTC, ocelotl approved these changes

2022-01-27 21:04 UTC, merged